In [4]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()

# Feature  names
print(iris.feature_names)
# Labels names
print(iris.target_names)

# Features values
print(iris.data[0])

# Label values
print(iris.target[0])

# Remove some data from iris table so we can use as test data
test_idx = [0, 50, 100]

test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

# Training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

# Tree classifier
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)


# Test
print(test_target)
print(clf.predict(test_data))


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0
[0 1 2]
[0 1 2]
